name: opa-pam-build-from-scratch

on:
  push:
    branches: 
    - master
    - develop
    - 'feature/**'
    paths-ignore:
    - '.vscode/**'
    - README.md
    - '.github/workflows/docker-pipeline.yml'
  pull_request:
    branches: 
    - master
    - develop
    - 'feature/**'

jobs:
  build:
    name: playground
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          set -e -x
          sudo apt-get install libpam0g-dev
          sudo apt-get install libcurl4-gnutls-dev
          sudo apt-get install autoconf
          sudo apt install sshpass

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout open-policy-agent/contrib
        uses: actions/checkout@v2
        with:
          repository: open-policy-agent/contrib
          ref: refs/heads/main
          path: contrib

      - name: Checkout akheron/jansson
        uses: actions/checkout@v2
        with:
          repository: akheron/jansson
          ref: refs/heads/master
          path: jansson

      - name: Setup akheron/jansson
        run: |
          set -e -x
          cd jansson
          sudo autoreconf -i
          ./configure --prefix=/usr && make
          sudo make install

      - name: Copy the pam module to /lib/x86_64-linux-gnu/security/
        run: |
          set -e -x 
          cd contrib/pam_opa/pam/ && make 
          sudo cp *.so /lib/x86_64-linux-gnu/security/

      - name: Configure OPA as PAM module
        run: |
          set -e -x
          sudo chmod 777 /etc/pam.d/sudo
          echo auth required /lib/x86_64-linux-gnu/security/pam_opa.so url=http://opa-auth-server.herokuapp.com:80 authz_endpoint=/v1/data/sshd/authz display_endpoint=/v1/data/display pull_endpoint=/v1/data/pull log_level=debug >> /etc/pam.d/sudo
          cat /etc/pam.d/sudo

      - name: SSH on same server using user 'ops'
        run: |
          sshpass -p ${{secrets.REMOTE_PASSWORD}} ssh -p 22 ops@localhost -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv
          sudo ls /
          exit
