name: opa-pam-build-from-scratch

on:
  push:
    branches: 
    - master
    - develop
    - 'feature/**'
    paths-ignore:
    - '.vscode/**'
    - README.md
    - '.github/workflows/docker-pipeline.yml'
  pull_request:
    branches: 
    - master
    - develop
    - 'feature/**'

jobs:
  build:
    name: playground
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          set -e -x
          sudo apt-get update -y
          sudo apt-get install -y libpam0g-dev libtool-bin libcurl4-gnutls-dev autoconf

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout open-policy-agent/contrib
        uses: actions/checkout@v2
        with:
          repository: open-policy-agent/contrib
          ref: refs/heads/main
          path: contrib

      - name: Checkout akheron/jansson
        uses: actions/checkout@v2
        with:
          repository: akheron/jansson
          ref: refs/heads/master
          path: jansson

      - name: Setup akheron/jansson
        run: |
          set -e -x
          cd jansson
          sudo autoreconf -i
          sudo ./configure --prefix=/usr && sudo make
          sudo make install

      - name: Copy the pam module to /lib/x86_64-linux-gnu/security/
        run: |
          set -e -x 
          cd contrib/pam_opa/pam/ && sudo make 
          sudo cp *.so /lib/x86_64-linux-gnu/security/

      - name: Configure OPA as PAM module
        run: |
          set -e -x
          sudo chmod 777 /etc/pam.d/sudo
          echo auth required /lib/x86_64-linux-gnu/security/pam_opa.so url=http://opa-auth-server.herokuapp.com:80 authz_endpoint=/v1/data/sudo/authz display_endpoint=/v1/data/display pull_endpoint=/v1/data/pull log_level=debug >> /etc/pam.d/sudo
          cat /etc/pam.d/sudo

      - name: Execute privileged command and test
        run: sudo visudo
