name: opa-pam-build-from-scratch

on:
  push:
    branches: 
    - master
    - develop
    - 'feature/**'
    paths-ignore:
    - '.vscode/**'
    - README.md
    - '.github/workflows/docker-pipeline.yml'
  pull_request:
    branches: 
    - master
    - develop
    - 'feature/**'

jobs:
  build:
    name: build-image
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          set -e -x
          sudo apt-get install libpam0g-dev
          sudo apt-get install libcurl4-gnutls-dev
          sudo apt-get install autoconf

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout open-policy-agent/contrib
        uses: actions/checkout@v2
        with:
          repository: open-policy-agent/contrib
          ref: refs/heads/main
          path: pam_opa

      - name: Checkout akheron/jansson
        uses: actions/checkout@v2
        with:
          repository: akheron/jansson
          ref: refs/heads/master
          path: jansson

      - name: Setup akheron/jansson
        run: |
          set -e -x
          cd jansson
          sudo autoreconf -i
          ./configure --prefix=/usr && make
          sudo make install